version: '3'
services:
  db:
    image: postgres:15.3-alpine3.18
    container_name: myapp-postgres-15.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    environment:
      POSTGRES_DB: myappdb
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
  redis:
    image: redis:7.2-rc-alpine3.18
    command: ["redis-server", "--port", "6400"]
    ports:
      - "6400:6400"
  myapp-web:
    build: .
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'&& sudo chown -R $USER:$USER ."
    environment:
      DB_HOST: db
      DB_NAME: myappdb
      DB_USERNAME: my_user
      DB_PASSWORD: 1234
      REDIS_URL: redis://redis:6400/0
    volumes:
      - .:/app:cached
    ports:
      - "4000:3000"
      - "22222:22"
    depends_on:
      - db
      - redis
volumes:
  postgres_data: {}
networks:
  default:
    name: myapp_default