development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
<<<<<<< HEAD
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6400/1" } %>
  channel_prefix: app_production
=======
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: blog_production
>>>>>>> origin/main
